"use client";
import { ReactNode, useEffect } from "react";
import { Inter } from "next/font/google";
import { Metadata } from "next";
import login from "./login/page.jsx"; // Corrected import statement
import { useRouter } from "next/navigation";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

interface RequireAuthProps {
  children: ReactNode;
}

const RequireAuth = ({ children }: RequireAuthProps) => {
  const currentUser = false; // Replace with actual authentication status
  const router = useRouter();

  useEffect(() => {
    // Redirect to the login page if the user is not authenticated
    if (!currentUser) {
      router.push("login");
    }
  }, [currentUser, router]);

  // Render the children only if authenticated
  return currentUser ? <>{children}</> : null;
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <RequireAuth>
          <div className="flex justify-center items-center">
            <div className="max-w-6xl lg:my-20 my-10 md:mx-10 mx-5">
              {children}
            </div>
          </div>
        </RequireAuth>
      </body>
    </html>
  );
}
