"use client";
import { ReactNode, useEffect } from "react";
import login from "./login/page.jsx";
import { useRouter } from "next/navigation";
import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";
import "./globals.css";


const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

interface RequireAuthProps {
  children: ReactNode;
}

const RequireAuth = ({ children }: RequireAuthProps) => {
  const currentUser = false; // Replace with actual authentication status
  const router = useRouter();

  useEffect(() => {
    // Redirect to the login page if the user is not authenticated
    if (!currentUser) {
      router.push("login");
    }
  }, [currentUser, router]);

  // Render the children only if authenticated
  return currentUser ? <>{children}</> : null;
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <RequireAuth>
          <div className="flex justify-center my-20 items-center">
          <div className="max-w-6xl">{children}</div>
        </div>
        </RequireAuth>
      </body>
    </html>
  );
}
